Merge branch 'development' of https://github.com/arendst/Tasmota into development
arendst/Tasmota pull request #15293
Opened 2022-04-04 20:15 UTC by benoitLecuppe

2022-04-04 20:31 UTC, barbudor commented
Please name your PR properly and re-insert the PR submission template
Also remove your changes in `platformio.ini`.

2022-04-05 09:08 UTC, arendst commented on tasmota/support_tasmota.ino
> +  if(value && !lastValue) {
Why this?

The ISR is called on a CHANGE of GPIO so this should ALWAYS be true.

2022-04-05 09:10 UTC, arendst commented on tasmota/xdrv_62_robotdyn.ino
> +
XDRV_62 is already in use. Change to XDRV_63

2022-04-05 09:13 UTC, arendst commented on tasmota/xdrv_62_robotdyn.ino
> +  if (!PinUsed(GPIO_ZEROCROSS))  AddLog(LOG_LEVEL_ERROR, PSTR("========== RBD INIT ERROR: on pin mist be set to ZC Pulse in template"));
Change all AddLog(LOG_LEVEL_x, PSTR("====) functions to AddLog(LOG_LEVEL_x, PSTR("RBD: ) in line with Tasmota logging.

Also use text strings as short as possible, You're not writing a book! It should be cheatsheet.

2022-04-05 09:21 UTC, arendst commented on tasmota/xdrv_62_robotdyn.ino
> +      rbdInit();
A driver needs to handle it's back off when there it is not configured by either selecting a unique GPIO or a setting. 

Your driver, once enabled in the compile, will report an error if GPIO_ZEROCROSS is not defined on any device. Not user friendly. 

It should also backoff servicing any other function call if it's not initialized correctly.

2022-04-05 20:15 UTC, ascillato requested changes
Please, take a look to the comments. Thanks.

2022-04-05 20:15 UTC, ascillato commented on tasmota/xdrv_63_robotdyn.ino
> +  #define USE_LIGHT
This line shouldn't be here. Please, delete it.

2022-04-05 20:15 UTC, ascillato commented on tasmota/xdrv_63_robotdyn.ino
> +  #define USE_ROBOTDYN_DIMMER
This #define should go in my_user_config.h file and it should go commented out. Please, move it to my_user_config.h as:

```cpp
// #define USE_ROBOTDYN_DIMMER
```

2022-04-05 20:15 UTC, ascillato commented on tasmota/xdrv_63_robotdyn.ino
> +  #define USE_ROBOTDYN_DIMMER
This #define should go in my_user_config.h file and it should go commented out. Please, move it to my_user_config.h as:

```cpp
// #define USE_ROBOTDYN_DIMMER
```

2022-04-05 20:17 UTC, ascillato commented
The CI Tests are failing due to redefinition of

```cpp
  #define USE_LIGHT
  #define USE_ROBOTDYN_DIMMER
```

Please, take a look to the comments. Thanks.

2022-04-06 08:55 UTC, benoitLecuppe commented
Hello everybody.
I'm sorry I didn't want to reintegrate my changes. it is a handling error. The program works well. but I'm not quite ready for reintegration
Benoit Lecuppe
French

2022-05-10 11:34 UTC, closed without merging