Support ESPC3 and ESPS3
arendst/Tasmota pull request #17791
Opened 2023-01-25 19:39 UTC by thkaiser

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.6
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2023-01-25 19:59 UTC, Jason2866 requested changes
Please remove this comment https://github.com/arendst/Tasmota/pull/17791/files#diff-7b48900d171b7b509f93b3524d46e5ec9af94c2b2cc046380d15acbd14b29cc4L135

2023-01-25 22:50 UTC, thkaiser commented
Sorry, I don't  understand which comment I have to remove. The multiple defines for the different architecture are intented.

2023-01-26 08:49 UTC, Jason2866 commented
Just the comment, is to remove

2023-01-26 08:58 UTC, Jason2866 approved these changes

2023-01-26 08:58 UTC, merged