Sml ams
arendst/Tasmota pull request #17828
Opened 2023-01-30 09:56 UTC by gemu2015

## Description:

**Related issue (if applicable):** fixes #8790
support for encrypted advances metering systems

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2023-01-30 10:31 UTC, Noschvie requested changes

2023-01-30 10:31 UTC, Noschvie commented on lib/lib_div/ams/library.properties
> +url=https://github.com/gskjold/AmsToMqttBridge
The project was renamed and changed to https://github.com/UtilitechAS/amsreader-firmware

2023-01-30 10:31 UTC, Noschvie commented on tasmota/tasmota_xsns_sensor/xsns_53_sml.ino
> +#include "han_Parser.h"
Duplicated #include statement

2023-01-30 10:31 UTC, Noschvie commented on tasmota/tasmota_xsns_sensor/xsns_53_sml.ino
> +				AddLog(LOG_LEVEL_INFO, PSTR(">> decrypted block: %d bytes"), len);
"SML:" instead of ">>", maybe log level shall be LOG_LEVEL_DEBUG

2023-01-30 10:31 UTC, Noschvie commented on tasmota/tasmota_xsns_sensor/xsns_53_sml.ino
> +					AddLog(LOG_LEVEL_INFO, PSTR(">> %02x - %d"),iob,sml_count);
"SML:" instead of ">>"

2023-01-30 10:31 UTC, Noschvie commented on tasmota/tasmota_xsns_sensor/xsns_53_sml.ino
> +	//AddLog(LOG_LEVEL_INFO, PSTR(">> %02x %02x %02x %02x"),pattern[0],pattern[1],pattern[2],pattern[3]);
"SML:" instead of ">>"

2023-01-30 10:31 UTC, Noschvie commented on tasmota/tasmota_xsns_sensor/xsns_53_sml.ino
> +			AddLog(LOG_LEVEL_INFO, PSTR("crypto mode used for meter %d"), mnum + 1);
Prefix "SML:" shall be added.

2023-01-30 10:34 UTC, Noschvie commented
@gemu2015 : well done, thanks!

2023-01-30 14:03 UTC, merged

2023-01-31 10:32 UTC, Jason2866 commented
@gemu2015 Build of one special version fails. Seems it is caused by this PR
https://github.com/Jason2866/Tasmota-build/actions/runs/4052872867/jobs/6972826399
Can you have a look?

2023-01-31 10:49 UTC, gemu2015 commented
ok there is one change that may cause this

the default version needs
#define USE_TLS
because encrypted meters become more important in the near future. 

or undefine decrypted mode by
#define NO_USE_SML_DECRYPT

2023-01-31 11:31 UTC, Jason2866 commented
Thx, will try `#define USE_TLS` first but i think it will need to much resources in this build.
So the second option will probably the one...