MS5837 and BMP280 functionality for inches water
arendst/Tasmota pull request #21377
Opened 2024-05-06 20:54 UTC by vtHydroponics

## Description: Added compatibility with MS5837 and BMP280 to calculate inches of water

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X ] The pull request is done against the latest development branch
  - [X ] Only relevant files were touched
  - [X ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X ] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [X ] The code change is tested and works with Tasmota core ESP32 V.3.0.0
  - [X ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2024-05-06 21:15 UTC, s-hadinger requested changes
Thanks. Multiple changes are needed

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/include/tasmota_configurations.h
> +#define USE_MS5837
Please don't change default configuraiont

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/include/tasmota_configurations_ESP32.h
> +#define USE_MS5837
Same

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/my_user_config.h
> +    #define USE_MS5837
Please disable by default (just add `// ` before it)

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_09_bmp.ino
> +  AddLog(LOG_LEVEL_DEBUG, PSTR("BMP_data{pressure:%f,temperature:%f,bmp_idx:%d}"), bmp_sensors[bmp_idx].bmp_pressure, bmp_sensors[bmp_idx].bmp_temperature, bmp_idx);
Why do you need this? Please remove, the syntax is not consistent with log format in Tasmota

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_128_ms5837.ino
> +    // consolidate to one line
It is easier to use %_f format, see https://tasmota.github.io/docs/Sensor-API/#extension-to-vsnprintf

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_128_ms5837.ino
> +  //if (!I2cEnabled(XI2C_98)) { return false; }
Why did you remove this? Please uncomment

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_14_sht3x.ino
> -#ifdef USE_SHT3X
Unrelated change, please revert

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_57_tsl2591.ino
> +    ResponseAppend_P(PSTR(",\"TSL2591\":{\"" D_JSON_ILLUMINANCE "\":%s}"), lux_str);
indentation is now incorrect, please revert

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_57_tsl2591.ino
> +tsl2591Gain_t gain_enum_array[4] = {TSL2591_GAIN_LOW,TSL2591_GAIN_MED,TSL2591_GAIN_HIGH,TSL2591_GAIN_MAX};
Please use `const` and `PROGMEM` for ESP8266

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xx2c_global/xsns_interface.ino
> +  &Xsns127,
Why not use 115 which is available

2024-05-06 21:15 UTC, s-hadinger commented on lib/lib_i2c/BlueRobotics_MS5837_Library/MS5837.cpp
> +	return (pressure(MS5837::Pa)-101300)/(fluidDensity*9.80665);
Please use float literals `9.80665f`

2024-05-06 21:15 UTC, s-hadinger commented on lib/lib_i2c/BlueRobotics_MS5837_Library/MS5837.cpp
> +	return (1-pow((pressure()/1013.25),.190284))*145366.45*.3048;
Please use float literals

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_128_ms5837.ino
> +#define XSNS_128            128
Please use 115 instead of 128

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_128_ms5837.ino
> +#define XI2C_98             98         // See I2CDEVICES.md
Please use next free value, which looks to be `88`

2024-05-06 21:15 UTC, s-hadinger commented on tasmota/tasmota_xx2c_global/xx2c_interface.ino
> -  XI2C_96
Please revert and use `88`

2024-05-06 21:15 UTC, s-hadinger commented on tools/decode-status.py
> +    "USE_SDM630","USE_LM75AD","USE_APDS9960","USE_TM1638","USE_MS5837"
I don't see how this is going to work since it was not added to the feature map

2024-05-07 07:59 UTC, arendst commented on tasmota/tasmota_xx2c_global/xsns_interface.ino
> +
DO NEVER CHANGE ANYTHING IN xsns_interface.ino !!!

This will break sensor enable/disable.

As suggested, use the next free slot.

2024-05-07 07:59 UTC, arendst commented on tasmota/tasmota_xx2c_global/xsns_interface.ino
> +
Ditto !!!

2024-05-07 08:00 UTC, arendst commented on tasmota/tasmota_xx2c_global/xx2c_interface.ino
>  #endif
SAME HERE. DO NOT CHANGE xx2c_interface.ino !!!

This breaks I2CDriver command

2024-05-07 08:03 UTC, arendst commented
The goal of a PR is to add functionality with touching as few files as possible.

You're touching files with adding spaces and irrelevant logs. There is even a TSL file change not related to your initial addition.

Pls revisit your PR and make as few changes as possible using the above suggestions.

2024-06-06 15:34 UTC, closed without merging