Compute US AQI and EPA AQI for PMS5003x sensors
arendst/Tasmota pull request #22294
Opened 2024-10-14 19:58 UTC by thomashargrove

## Description: 

AQI is a common way to display PM2.5 data.  This PR adds a calculation for US AQI, and a second one that uses the US EPA adjustments which gives a more accurate AQI for places that experience wildfire smoke.  

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [ ] The code change is tested and works with Tasmota core ESP32 V.3.1.0.240926
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2024-10-14 20:26 UTC, s-hadinger requested changes
Nice, please apply the suggested changes to make code smaller

2024-10-14 20:26 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_18_pms5003.ino
> +    return 0.524 * x - 0.0862 * RH + 5.75;
All literals must be forced to floats using `f` suffix, like `0.524f`. Otherwise computation is done using double, which eats up a lot of flash.

2024-10-14 20:26 UTC, s-hadinger commented on tasmota/tasmota_xsns_sensor/xsns_18_pms5003.ino
> +    return 2.966 + 0.69 * x + 8.84 * pow(10.0, -4.0) * pow(x, 2.0);
Please use `FastPrecisePowf()` instead of `pow()` to use a smaller implementation

2024-10-14 20:50 UTC, thomashargrove commented
Thanks, made the requested changes

2024-10-14 20:53 UTC, arendst commented
Nice to know in Europe that their AQI is US approved.

2024-10-14 21:06 UTC, arendst commented
Any chance you're able to add the European (or Celsius based results) too? 

If not I suggest to make the provision for US specific data related to the user selection of Fahrenheit and remove US specific data if user has selected Celsius.

2024-10-14 21:18 UTC, thomashargrove commented
Yeah happy to add Europe AQI

2024-10-14 23:32 UTC, thomashargrove commented
In Fahrenheit

```
16:29:15.928 MQT: tele/Home_Garage_AQI/SENSOR = {"Time":"2024-10-14T16:29:15","PMS5003T":{"CF1":1,"CF2.5":3,"CF10":3,"PM1":1,"PM2.5":3,"PM10":3,"US_AQI":16,"PB0.3":336,"PB0.5":99,"PB1":16,"PB2.5":5,"Temperature":68.0,"Humidity":58.9,"DewPoint":53.1,"US_EPA_AQI":11},"TempUnit":"F"}
```

![image](https://github.com/user-attachments/assets/21a18e77-cfb9-47d7-a831-bde97fc16331)

and Celcius

```
16:30:15.915 MQT: tele/Home_Garage_AQI/SENSOR = {"Time":"2024-10-14T16:30:15","PMS5003T":{"CF1":1,"CF2.5":3,"CF10":3,"PM1":1,"PM2.5":3,"PM10":3,"EAQI":"Good","PB0.3":336,"PB0.5":99,"PB1":16,"PB2.5":5,"Temperature":20.0,"Humidity":58.9,"DewPoint":11.7},"TempUnit":"C"}
```

![image](https://github.com/user-attachments/assets/d8b8a723-5c85-474f-8a5a-06999d0a1b2c)

2024-10-14 23:35 UTC, thomashargrove commented on tasmota/tasmota_xsns_sensor/xsns_18_pms5003.ino
>      if (json) {
This section of code was inconsistent with trailing commas.  I changed it so each new json string we append starts with a comma and does not have a trailing comma

2024-10-14 23:37 UTC, thomashargrove commented
I went with string labels for European Air Quality Index.  I could not find a numeric scale like the 0-500 one in the US.  Let me know if that seems correct.

2024-10-15 08:22 UTC, arendst commented
Thx.

I will have a look regarding the string labels. As it stands we need translations for all english terms shown in the GUI. I'll see how to  get rid of some (Like European and US).

2024-10-15 08:56 UTC, s-hadinger approved these changes

2024-10-25 12:24 UTC, arendst commented
Did some research regarding non-US AQI and as expected it's a can of worms ;-)

In short almost every country uses a different calculation of PM2.5 to get to some kind of AQI. See https://en.wikipedia.org/wiki/Air_quality_index. Considering this I strongly feel this calculation needs to be done on the front-end based on Tasmota provided data.

Therefore I'll remove the current European calculation and keep the US one based on Fahrenheit.

2024-10-25 12:45 UTC, arendst commented
Kind of merged this without the celsius part just now. Thx.

2024-10-25 12:45 UTC, closed without merging