Add MDNS enable in Web UI
arendst/Tasmota pull request #22602
Opened 2024-12-07 15:19 UTC by cristiklein

## Description:

This allows the awesome MDNS advertise feature to be easier to discover and enable for novice users. See screenshot below.

![image](https://github.com/user-attachments/assets/dd9df8ac-6102-4bf9-8887-4ab486daee02)

May I use the space in this PR to express the awesomeness of this project. I'm not a stranger to embedded development, but have never worked with PlatformIO or Tasmota before. Few hours later, I can build my own firmware and contribute to this project. Kudos!

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

Note to review: I didn't find guidance on how to perform testing against Tasmota core ESP8266 V.2.7.8 and Tasmota core ESP32 V.3.1.0.241206. Please provide me with guidance and I'll perform the tests.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [ ] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241206
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2024-12-07 15:51 UTC, s-hadinger requested changes
Thanks but your PR is broken on multiple levels: missing languages and guarding with `USE_DISCOVERY`.

Overall MDNS is a feature that brings most problems than it solves, I'm not sure we want to surface it in the GUI. As it is only for advanced users that know what they are doing, I recommend not to add it.

2024-12-07 15:51 UTC, s-hadinger commented on tasmota/language/en_GB.h
> +#define D_MDNS_ENABLE "MDNS enable"
The define must be done in every language file, not just English

2024-12-07 15:51 UTC, s-hadinger commented on tasmota/tasmota_xdrv_driver/xdrv_01_9_webserver.ino
> +  "<label><input id='b4' type='checkbox'%s><b>" D_MDNS_ENABLE "</b></label><br>"
This must be guarded by `#ifdef USE_DISCOVERY` to not show it when MDNS is not present in the build

2024-12-07 15:51 UTC, s-hadinger commented on tasmota/tasmota_xdrv_driver/xdrv_01_9_webserver.ino
> +    (Settings->flag3.mdns_enabled) ? PSTR(" checked") : "",   // SetOption55 - Enable MDNS
Guard with `#ifdef USE_DISCOVERY`

2024-12-07 15:51 UTC, s-hadinger commented on tasmota/tasmota_xdrv_driver/xdrv_01_9_webserver.ino
> +  cmnd += Webserver->hasArg(F("b4"));
Guard with `#ifdef USE_DISCOVERY`

2024-12-07 15:55 UTC, Jason2866 commented
There is no mDNS support in the esp8266 precompiled builds and there will be never (horrible faulty and eats up to much flash).
mDNS is only activated in esp32 builds where Matter is active (Matter needs parts of mDNS services)
And mDNS is everything than great it is by design a mess!

2024-12-07 21:50 UTC, arendst commented
Thx for your work.

As you noticed we hate mDNS as it uses way to much code space and except for Matter it isn't really needed once you've managed to install a simple DNS server in your home environment.

2024-12-07 21:50 UTC, closed without merging

2024-12-09 09:01 UTC, cristiklein commented
I agree. Thanks folks for taking the time to look at my PR and give me feedback. It was good practice for me and I hope I'll come with a more useful PR next time. (Although, to be honest, the project feels rather finished, so I'm unsure what that could be.)