Added Tx20 Wind Sensor
arendst/Tasmota pull request #3146
Opened 2018-07-06 23:00 UTC by TheEggi

Details of the sensor can be found in this issue:
https://github.com/arendst/Sonoff-Tasmota/issues/2654

The wind sensor consist of:
- red cable (vcc)
- yellow (gnd)
- black cable (transmit) - can be configured using UI
- green cable (starts transmission - should be connected to gnd)

Config:
![image](https://user-images.githubusercontent.com/1206407/42403326-ab3c97f8-8180-11e8-99c0-7be9acefe3d6.png)

Result:
![image](https://user-images.githubusercontent.com/1206407/42403363-f560d2a4-8180-11e8-8fd9-a2479843debb.png)

Json Result:
"TX20":{"SPEED_AVG:":nan, "SPEED_MAX":0.00, "DIRECTION":"NNE"}

2018-07-09 13:43 UTC, TheEggi commented
To be honest ... I don't have anything that I could compare it to. I mean the position is marked on the sensor and seems to work as expected but for the wind speed the only test that I could do was to blow at it and see if the speed is increasing/decreasing - and that seemed to have worked. If you have a better way/idea (without any real testing equipment) how I can test the precision of the device, I am more than happy to try it.

2018-07-09 14:20 UTC, Jason2866 commented
I think i buy one. I can compare it with the quality (expensive) Aneometer from my brother (hang gliding...)
Thx

2018-07-11 13:53 UTC, Silencer80 commented
Thank you very much @TheEggi for implementing this! 

I have just returned from a businesstrip and have a lot of work to do. However, I already have a NodeMCU and a TX20 sensor on my desk to test that as soon as possible. 

I'm so curious if that works well. I can compare the results with my mdt SCN-WS3HW.01 Weatherstation.

Thank you again!
-Boris

2018-10-04 10:15 UTC, FabianHM commented
Hello, 
What are the chances that Tasmota's support will be short-term? I could buy the device just under 30 € but would not buy it without Tasmota use.
Greetings Fabian

2018-10-04 16:41 UTC, Jason2866 commented
@FabianHM 
Dont hesitate. Buy one it works with the fork from @TheEggi

2018-10-17 16:32 UTC, ascillato requested changes

2018-10-17 16:32 UTC, ascillato commented on sonoff/sonoff.ino
> +  XsnsCall(FUNC_LOOP);
Hi, This line shouldn't be there.

Please, check other sensors to see the way tasmota handle this.

2018-10-17 16:32 UTC, ascillato commented on sonoff/xsns_91_tx20.ino
> +
You need to add a 
```suggestion
#ifdef USE_TX20_wind_sensor
```
in order to enable or disable this sensor from user_config.h file

By default this sensor should be disabled in user_config.h

2018-10-17 16:32 UTC, ascillato commented on sonoff/xsns_91_tx20.ino
> +}
Add below this a
#endif // enable sensor

2018-10-17 16:34 UTC, ascillato commented
@TheEggi 

This PR has been rebased with the new version of Tasmota.

Could you update it?

2018-10-18 18:32 UTC, FabianHM commented
> 
> 
> Details of the sensor can be found in this issue:
> #2654
> 
> The wind sensor consist of:
> 
>     * red cable (vcc)
> 
>     * yellow (gnd)
> 
>     * black cable (transmit) - can be configured using UI
> 
>     * green cable (starts transmission - should be connected to gnd)
> 
> 
> Config:
> ![image](https://user-images.githubusercontent.com/1206407/42403326-ab3c97f8-8180-11e8-99c0-7be9acefe3d6.png)
> 
> Result:
> ![image](https://user-images.githubusercontent.com/1206407/42403363-f560d2a4-8180-11e8-8fd9-a2479843debb.png)
> 
> Json Result:
> "TX20":{"SPEED_AVG:":nan, "SPEED_MAX":0.00, "DIRECTION":"NNE"}

What does the analogue input in screenshot "10" indicate?

2018-10-18 19:16 UTC, ascillato commented
Means that in his version he has enabled the use of the Analog input on the pin A0 but nothing is connected there. Just that. Nothing to do with this PR nor the sensor. Don't worry.

2018-10-20 07:56 UTC, TheEggi commented
Added most of your suggestions. Maybe you have a suggestion on which sensor I could check as an example to remove the FUNC_LOOP.

2018-10-21 08:05 UTC, Jason2866 commented
Hello together,
i have bought a TX20 this week. Happy to test when the "final" version is done.

2018-10-21 10:46 UTC, closed without merging

2018-10-21 10:46 UTC, arendst commented
Just released a version for the TX20. Give it a try and let me know if it works pls.

2018-10-21 12:38 UTC, TheEggi commented
Seems to be working. Thank you for adding it.

2018-10-28 12:57 UTC, Jason2866 commented
Thx for programming and adding.
![image](https://user-images.githubusercontent.com/24528715/47616165-626e4980-dab9-11e8-9709-e71bcfa6a1e8.png)

2018-10-28 13:08 UTC, arendst commented
Thx for testing ;-)

2018-11-20 09:01 UTC, Sepultura22 commented
Hi, I have a doubt. I bought a TX20 sensor and it does not work for me. I have loaded the latest tastmota firmware in a basic sonoff and soldered the black cable in gpio4, the yellow and green cable in gnd and the red in vcc. I have also selected in the configuration that gpio4 acts with TX20. Should we do more? Thank you very much for your work, it is just what I was looking for.

2018-12-08 10:38 UTC, travelling-man commented
Hello,

I have a problem that only updates the wind direction. The speed doesn't change and stays at 0.0 km/h permanently.

Does anyone have similar problems?

2018-12-08 10:47 UTC, Jason2866 commented
Nope, works fine for me

2018-12-08 11:02 UTC, FabianHM commented
it works fine for me too. No Problems

2018-12-08 11:42 UTC, travelling-man commented
what hardware do you use?

All cables (red -> 3,3v) (green, red -> gnd) (black -> d2) are already connected before starting the Wemos.

I am using a Wemos d1 mini and its 3,3v.

Strange is that the wind direction is updated.

Is there a way to debug it?

2018-12-08 13:52 UTC, Jason2866 commented
![20181208_144849](https://user-images.githubusercontent.com/24528715/49686711-cc3a3400-faf8-11e8-9312-7a9cd56313ed.jpg)
Just this...

2018-12-08 13:53 UTC, Jason2866 commented
Isnt installed because solar charging part isnt done right now...

2019-10-03 22:00 UTC, travelling-man commented
> I cut the cable down to ~1.5m as I did not need it to be any longer - worked without any issues.

Can you take a picture with the model number?

2019-11-03 06:53 UTC, travelling-man commented
Does anyone still have a photo with the original pin assignment?

2020-02-02 21:30 UTC, davide5681 commented
e possibile direttente da taota abilitare un us ita una volta arrivati ad una sohlia di vrlocita?

2020-02-02 21:31 UTC, davide5681 commented
e possibile direttamente da tasmota abilitare un uscita una volta arrivati ad una soglia  di velocità ?

2020-02-08 14:15 UTC, Pastant commented
I tried the TX23 because the TX20 is not available any longer. The TX23 is not compatible! Even the support for the TX20 was dropped in recent releases (8.1) ...

2020-02-08 16:26 UTC, Jason2866 commented
Support for TX20 is NOT dropped. It is just not in a precompiled version (as many other drivers)
Read section self compile in the documentation www.tasmota.com

2020-02-08 18:44 UTC, Pastant commented
The "Complete list of available feature and sensors." states that tasmota-sensors.bin supports the TX20. So the precompiled supprt is dropped. I won't compile a version because I only own a TX23 which is not compatible ...

2020-02-19 15:05 UTC, curzon01 commented
I'm currently trying to adapt the TX20 driver also for TX23. The protocol is the same but TX23 needs an initial signal to send out their data where TX20 sends every 2 seconds automatically.