Add support for 5 LEDs
arendst/Tasmota pull request #3765
Opened 2018-09-11 15:58 UTC by galak

The MJ-SD01 dimmer switch has 5 LEDs each tied to its own GPIO so bump up
the max number of LEDS to 5.

Signed-off-by: Kumar Gala <kumar.gala@gmail.com>

2018-09-11 16:19 UTC, ascillato requested changes
Hi, these changes are backward incompatible. If someone updates will have all settings scrambled.

Sorry that your proposal got complicated with compatibility.

2018-09-11 20:41 UTC, galak commented
> Hi, these changes are backward incompatible. If someone updates will have all settings scrambled

Is there a way to make it backward compatible?

2018-09-13 01:16 UTC, ascillato2 requested changes
> Is there a way to make it backward compatible?

could be an extra routine to see if the eeprom config is from a lower version and converts it to your new config structure, for example.

2018-10-01 12:39 UTC, ascillato2 commented
Thanks for sharing your ideas. By now, This PR is not going to be merged due to be outside the actual scope of Tasmota. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

2018-10-01 12:39 UTC, closed without merging