WIP - Add support for DHT sensor discovery
arendst/Tasmota pull request #4380
Opened 2018-11-18 14:36 UTC by emontnemery

Work in progress - Needs review

2018-11-18 14:39 UTC, emontnemery commented
@arendst Do you think it's OK to add the support for announcing temperature/humidity sensors in xdrv_12_home_assistant.ino? My main concern is the dependency to the below declarations, which I now moved to `sonoff.ino`
Let me know if you prefer some other way.

``` c++
#define DHT_MAX_SENSORS  3
extern byte dht_sensors;
extern struct DHTSTRUCT {
  byte     pin;
  byte     type;
  char     stype[12];
  uint32_t lastreadtime;
  uint8_t  lastresult;
  float    t = NAN;
  float    h = NAN;
} Dht[];
```

2018-11-18 16:41 UTC, arendst commented
I don't like the declaration in sonoff.ino as it makes the sensor code no longer a separate unit.

As you mention the string parsing looks more promising. Pls try it that way.

2018-11-20 20:03 UTC, ascillato2 requested changes
Hi,

Thanks for working on this. This feature was requested several times.

Can you make the changes to be only in xdrv_12_home_assistant.ino ?

Thanks

2018-11-20 21:10 UTC, emontnemery commented
@ascillato Yes, I'll refactor.
By the way, what sensor type is most wanted in your opinion?

2018-11-20 21:12 UTC, ascillato2 commented
> @ascillato Yes, I'll refactor.

great :+1: 

> By the way, what sensor type is most wanted in your opinion?

The most asked where temp sensors.

2018-11-20 21:16 UTC, emontnemery commented
Thanks, I'll push an update later this week

2018-11-21 18:31 UTC, emontnemery commented
@arendst , @ascillato2 Refactored to base on string matching. Please review and let me know if any concerns.
As written in the description, special support for battery, illuminance and presure can also be added if desired.

2018-11-21 19:25 UTC, ascillato approved these changes

2018-11-21 19:29 UTC, ascillato2 approved these changes

2018-11-22 11:16 UTC, merged