Implemented automatic setting of clock display from network time.
arendst/Tasmota pull request #6034
Opened 2019-07-07 10:44 UTC by adebeun

## Description:
The display of the AZ7798 CO2 meter includes a clock showing date and time.This is normally set manually but slowly drifts or is reset when the power is off for too long. This enhancement automatically sets the clock time from the network time, shortly after power on and then every 24 hours thereafter.

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched (Also remember to add to _changelog.ino_ file without updating version)
  - [ ] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works.
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ ] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

2019-07-07 11:59 UTC, ascillato commented
Hi,

Please complete the checklist. Thanks

2019-07-08 12:32 UTC, arendst requested changes
Pls remove changes from _changelog.ino as it interferes with current file.

2019-07-08 19:05 UTC, merged

2019-07-08 19:10 UTC, adebeun commented
You checklist confused me. The second item includes "(Also remember to add to changelog.ino file without updating version)". What do you mean by that?

2019-07-08 19:14 UTC, arendst commented
I know. I'll remove it as I want PR's to be as small  as possible.

2019-07-08 19:14 UTC, ascillato commented
@adebeun 

Don't worry. You did ok. But then, the changelog was updated and your PR was rebased for that. That is why Theo asked to remove that in order to make the merge possible.

Thanks :+1: