Translations for xsns_53_sml.ino en-GB and pt-PT
arendst/Tasmota pull request #7917
Opened 2020-03-14 17:28 UTC by tiagofreire-pt

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core Tasmota_core_stage
  - [X] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

2020-03-14 18:25 UTC, Jason2866 commented
If you do language adaptions, ALL language files have to be touched.
You can copy in all other languages files the english content.
The community will do the translation.

2020-03-14 18:34 UTC, tiagofreire-pt commented
> 
> 
> If you do language adaptions, ALL language files have to be touched.
> Please copy the original content from german in german language file
> You can copy in all other languages files the english content.
> 
> The community will do the translation.

Done. :)

2020-03-14 18:49 UTC, Jason2866 commented
Please merge the german translation PR in your PR :-)

2020-03-14 19:35 UTC, tiagofreire-pt commented
> 
> 
> Please merge the german translation PR in your PR :-)

Done. Tks! :)

2020-03-14 21:25 UTC, ascillato2 requested changes
Duplicated entries on en-GB-h file

EDIT: fixed.

2020-03-14 21:25 UTC, ascillato2 commented on tasmota/language/en-GB.h
> +// xsns_53_sml.ino
Duplicated entries

2020-03-14 21:28 UTC, ascillato2 commented on tasmota/language/en-GB.h
> +// xsns_53_sml.ino
Fixed

2020-03-14 21:35 UTC, ascillato2 approved these changes

2020-03-15 08:21 UTC, merged

2020-03-15 14:32 UTC, kugelkopf123 commented
I don't want to be a spoiler, but as far as I can see this whole translation thing is no longer necessary. The translation only applies if the hard code counter is implemented. This approach has not been developed since the xdrv_10_scripter.
All settings including the naming of the values are now made in the scripter.
So actually that's a lot of unnecessary code. Maybe @gemu2015 can say something about it.

2020-03-15 15:25 UTC, Jason2866 commented
If you have one of these ```#define EHZ161_0 1
#define EHZ161_1 2
#define EHZ363 3
#define EHZH 4
#define EDL300 5
#define Q3B 6
#define COMBO3 7
#define COMBO2 8
#define COMBO3a 9
#define Q3B_V1 10
#define EHZ363_2 11
#define COMBO3b 12
#define WGS_COMBO 13
#define EBZD_G 14```
and you do not want to use scripter this driver does still his job.

2020-03-15 16:04 UTC, kugelkopf123 commented
Sure it does!
But wouldn't it save some memory/Flash to remove everything like this from the code and just let it run through the scripter? Apart from that, the standard code that appears after activation of this Driver eg. (OBIS) always leads to confusion.

2020-03-15 17:39 UTC, Jason2866 commented
@kugelkopf123 
No it does save nothing dropping this driver since `USE_SML_M` is not enabled in any
Tasmota precompiled builds.

So only users which do there own build(s) can activate this driver, i am sure the know what the do.
No reason to drop a working driver that gives a different oppertunity to use.

2020-03-15 19:11 UTC, kugelkopf123 commented
> @kugelkopf123
> No it does save nothing dropping this driver since `USE_SML_M` is not enabled in any
> Tasmota precompiled builds.
> 
Okay!

> So only users which do there own build(s) can activate this driver, i am sure the know what the do.
Thats funny! I would suggest that you look into the threads over this driver. It is shurly 
> No reason to drop a working driver that gives a different oppertunity to use.


That is a very amusing statement.
I would suggest you check out the forums dealing with this driver. It's really a fantastic driver, no question about it. But to say that the people who activate it know what they're doing is going too far.
I'm pretty active in the SML community and I know what I'm talking about. For this reason I have already written a complete tutorial for it and also started to revise the tasmota wiki.

It was just a suggestion to remove this complete hardcoded meter option. I assumed that it would probably save space and maybe some things in the configuration would be easier to understand for beginners.