Add `DimmerStep` command
arendst/Tasmota pull request #9733
Opened 2020-11-04 09:49 UTC by jamesturton

Signed-off-by: Scoobler <jamienwood@hotmail.com>

## Description:
Add `DimmerStep` to allow an auto (+/-) value to be set between 0...50 instead of the fixed value of 10 which creates a very quick step when using rules for dimming. Default value remains 10.

**Related issue (if applicable):** fixes arendst#9669

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.5
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2020-11-04 09:52 UTC, jamesturton commented
@Scoobler I made one small change to your PR which was to change the valid range of `DimmerStep` to be between 0..50 instead of 0..10 in case people want to have less steps. If you are ok with this then I shall mark this PR as ready for review.

2020-11-04 14:15 UTC, arendst commented on tasmota/xdrv_04_light.ino
> +
Pls replace function with this:
```
void CmndDimmerStep(void) {
  // DimmerStep       - Show current dimmer step as used by Dimmer +/-
  // DimmerStep 1..50 - Set dimmer step
  if (XdrvMailbox.data_len > 0) {
    if (XdrvMailbox.payload < 1) {
       Settings.dimmer_step = 1;
    } else if (XdrvMailbox.payload > 50) {
      Settings.dimmer_step = 50;
    } else {
      Settings.dimmer_step = XdrvMailbox.payload;
    }
  }
  ResponseCmndNumber(Settings.dimmer_step);
}
```

2020-11-04 14:16 UTC, arendst requested changes
Other than my suggested change it looks ready for merge.

2020-11-04 18:11 UTC, arendst commented
Thx. about to merge. Looking forward to your shelly stuff.

2020-11-04 18:12 UTC, merged

2020-11-04 22:53 UTC, Scoobler commented
@jamesturton looks great, from testing even a value of 10 was a very high - but it’s good to give people the option to tune to all the different needs out there!

2022-01-24 03:06 UTC, kmatokov commented
does that still read only or i just can't set it else than 10 ?

2022-01-24 07:47 UTC, barbudor commented
`DimmerStep` is just working fine.
As you don't give any details on what's you are doing, don't expect any details on what's you're doing wrong

2022-01-24 13:19 UTC, kmatokov commented
yup you are right, i didn't provided much info's, because i thought that this treed is just about DimmerStep.... I just wandered if DimmerStep feature is still "hard-coded" (as i read it once was) to 10 because i tried to change it to 5 or other number, but my rules on long-press which trigger + and - continue to increase or decrease it for a 10 even i let DimmerStep  5 or less so i didn't figured out how to soften that dimming steps, thanks, and i'm not sure what release i used yesterday, but some ver 10xx from special tasmota platinum, but then i tested with "usual" last tasmota and same +/- 10 steps inc/dec. when using rules, thx.

2022-01-24 14:41 UTC, barbudor commented
At least with latest development version:
```
08:45:01.722 CMD: dimmer
08:45:01.729 MQT: stat/nodemcu/DIMMER = {"Dimmer":10}
08:45:09.355 CMD: dimmer +
08:45:09.365 MQT: stat/nodemcu/DIMMER = {"POWER":"ON","Dimmer":20}
08:45:20.769 CMD: dimmerstep 5
08:45:20.775 MQT: stat/nodemcu/DIMMERSTEP = {"DimmerStep":5}
08:45:24.786 CMD: dimmer +
08:45:24.793 MQT: stat/nodemcu/DIMMER = {"POWER":"ON","Dimmer":25}
08:45:30.275 CMD: dimmerstep 30
08:45:30.281 MQT: stat/nodemcu/DIMMERSTEP = {"DimmerStep":30}
08:45:34.900 CMD: dimmer +
08:45:34.907 MQT: stat/nodemcu/DIMMER = {"POWER":"ON","Dimmer":55}
```

2022-01-24 20:32 UTC, kmatokov commented
ok, i probably can't use it as i use 4 pwm channels and "normal" dimmer not work for me, so i had to fix rules to use channel1 instead dimmer and it work, but  
```
21:20:34.000 MQT: stat/tasmota_A5825C/RESULT = {"DimmerStep":7}
21:20:47.343 CMD: Dimmer1 +
21:20:47.351 MQT: stat/tasmota_A5825C/RESULT = {"POWER1":"ON","Channel1":100,"POWER2":"OFF","Channel2":100,"POWER3":"OFF","Channel3":100,"POWER4":"OFF","Channel4":100,"Color":"FFFFFFFF"}
21:20:56.184 CMD: Dimmer1 -
21:20:56.192 MQT: stat/tasmota_A5825C/RESULT = {"POWER1":"ON","Channel1":100,"POWER2":"OFF","Channel2":100,"POWER3":"OFF","Channel3":100,"POWER4":"OFF","Channel4":100,"Color":"FFFFFFFF"}
21:21:11.187 CMD: channel1 -
21:21:11.195 MQT: stat/tasmota_A5825C/RESULT = {"POWER1":"ON","Channel1":90,"POWER2":"OFF","Channel2":100,"POWER3":"OFF","Channel3":100,"POWER4":"OFF","Channel4":100,"Color":"E5FFFFFF"}
21:21:22.419 CMD: Dimmer -
``` 
maybe DimmerStep not work on 4 channel configuration (because has no effect on channels)
I'm relatively new on tasmota so i "grabbing in dark" or better say brute-forcing as i couldn't find how to use rules on multi channel soft-pwm but i somehow tapped on it by random testing
```
Rule1 
on system#boot do var1 + ENDON
on switch1#state=2 do POWER TOGGLE ENDON
on switch1#state=4 do Channel1 %var1% ENDON
on switch1#state=7 do event upordown=%var1% ENDON
on event#upordown=+ do var1 - ENDON
on event#upordown=- do var1 + ENDON
```
this now hardly exits from thread but if someone can point me how to use local longpress rules for channels but with DimmerStep having effect on individual or global channels

thx :)